apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sample-k8s-scope
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'iot-sim-static'
        static_configs:
          - targets:
              - 'sample-prometheus-iot-sim:8085'

      - job_name: 'analysis-engine'
        static_configs:
          - targets:
              - 'analysis-engine-instance:8086'

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['sample-k8s-scope']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __address__]
            action: replace
            target_label: __address__
            regex: (.*);(.*)
            replacement: ${2}:${1}
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
