apiVersion: solution.symphony/v1
kind: Solution
metadata:
  name: sample-prometheus-v-1
spec:
  rootResource: sample-prometheus
  metadata:
    deployment.replicas: "#1"
    service.ports: "[{\"name\":\"port9090\",\"port\":9090}]"
    service.type: "LoadBalancer"
  components:
    - name: sample-prometheus
      type: container
      properties:
        container.image: "prom/prometheus:latest"
        container.imagePullPolicy: "IfNotPresent"
        container.ports: "[{\"containerPort\":9090,\"protocol\":\"TCP\"}]"
